### PR TITLE
Carl Flor's Submission of Global Ranking

### PR DESCRIPTION
**Pull request by carlflor**
- Adds global ranking for girls at pages#index

### CODE REVIEW

**Comment by davidsiaw** [comment]
Seems like a few people have trouble encrypting the message. Could you please email me the info instead?

**Comment by carlflor** [comment]
Got it! I'm not quite sure which email I should send it to. Is this corret: `davidsiaw@airtidy.com` (based on readme.md - david アット airtidy.com )?

**Comment by davidsiaw** [comment]
Hi Carl, sorry about the late reply. just replace アット with the @ symbol. Thanks

**Comment by carlflor** [comment]
no problem! got it! :)

**Comment by davidsiaw** [comment]
Thanks for your application

**Pull request closed without merging**
