### PR TITLE
[WIP] Girls global ranking

### PR DESCRIPTION
**Pull request by tannakartikey**
Tests and other details coming shortly!
reference: upwork.com

### CODE REVIEW

**Comment by davidsiaw** [comment]
Thanks for your pull request! I will review it and be in touch with you soon!

**Comment by davidsiaw** [comment]
You haven't added in an encrypted message. Please add one so we can get in touch when you are done with the work in progress

**Comment by tannakartikey** [comment]
Sure. Will do that shortly.
Thanks.

**Comment by tannakartikey** [comment]
Sorry for not sending it yet. Is it any good, for future, if I send it now?

**Comment by tannakartikey** [comment]
@davidsiaw

**Pull request closed without merging**
