### PR TITLE
Adds the method to get the best girls ranking

### PR DESCRIPTION
**Pull request by AndresAbed**
Shows the best girls ranking into the index view

### CODE REVIEW

**Comment by davidsiaw** [comment]
Thank you for your submission. I will review your submission and be in touch!

**Comment by davidsiaw** [comment]
You haven't added in an encrypted message. Please add one so we can get in touch

**Comment by davidsiaw** [comment]
You haven't added in an encrypted message. Please add one so we can get in touch

**Comment by AndresAbed** [comment]
Justin has all my contact information already.

**Pull request closed without merging**
