### PR TITLE
Diego Raggio's Job Application

### PR DESCRIPTION
**Pull request by DidiRaggio**
Updated the Pull request to include the DB migrations that had not been pushed.

### CODE REVIEW

**Comment by davidsiaw** [comment]
Hi Diego, Sorry about the extremely late reply. I we will be in touch soon!

**Comment by DidiRaggio** [comment]
No worries, let me know if you have any questions or observations a all. I can always make last minute adjustments.

**Comment by davidsiaw** [comment]
Thanks for your pull request. Will be in touch by e-mail

**Comment by DidiRaggio** [comment]
Hey David, I never got your email. Did you ever send one to me? Just for peace of mind...

**Pull request closed without merging**
